"""Agent-written Python execution for demo analysis artifacts.

No sandbox by user choice: this runs in the same Python environment as the server, but
in a temp working directory and a subprocess so timeouts can kill runaway code.
"""
from __future__ import annotations

import os
import subprocess
import sys
import tempfile
import textwrap
import uuid
from pathlib import Path

from langchain_core.tools import StructuredTool

from ...config import settings
from .. import persistence
from ..events import CodePayload, DocumentArtifact
from ..tools import CURRENT_EMITTER, _in_thread

_EXT_TO_FORMAT = {
    ".pdf": "pdf",
    ".png": "png",
    ".svg": "svg",
    ".csv": "csv",
    ".json": "json",
    ".html": "html",
    ".txt": "text",
    ".md": "text",
}


def build_python_tool(session_id: str, run_id: str) -> StructuredTool:
    def _run_python(code: str, purpose: str = "analysis") -> str:
        code = textwrap.dedent(code or "").strip()
        if not code:
            return "No Python code supplied."
        emitter = CURRENT_EMITTER.get()
        with tempfile.TemporaryDirectory(prefix="ksp-agent-code-") as tmp:
            workdir = Path(tmp)
            script = workdir / "analysis.py"
            script.write_text(code, encoding="utf-8")

            def _execute(handle=None) -> str:
                step_id = getattr(handle, "id", None)
                if emitter:
                    emitter.code(CodePayload(step_id=step_id, phase="executing", code=code, language="python"))
                env = {**os.environ, "MPLBACKEND": "Agg"}
                try:
                    proc = subprocess.run(
                        [sys.executable, str(script)],
                        cwd=workdir,
                        env=env,
                        text=True,
                        capture_output=True,
                        timeout=settings.assistant_code_timeout_seconds,
                    )
                    stdout, stderr, exit_code = proc.stdout, proc.stderr, proc.returncode
                except subprocess.TimeoutExpired as exc:
                    stdout = exc.stdout or ""
                    stderr = (exc.stderr or "") + f"\nTimed out after {settings.assistant_code_timeout_seconds}s."
                    exit_code = 124

                artifacts: list[str] = []
                for path in sorted(workdir.iterdir()):
                    if path.name == script.name or not path.is_file():
                        continue
                    fmt = _EXT_TO_FORMAT.get(path.suffix.lower())
                    if not fmt:
                        continue
                    artifact_id = f"doc-{uuid.uuid4().hex[:8]}"
                    document = DocumentArtifact(
                        id=artifact_id,
                        title=path.name,
                        format=fmt,  # type: ignore[arg-type]
                        url=f"/api/v1/assistant/artifacts/{artifact_id}",
                        caption=f"Generated by Python for {purpose}.",
                    )
                    persistence.save_artifact(document, session_id, run_id)
                    persistence.save_blob(artifact_id, path.read_bytes())
                    artifacts.append(path.name)
                    if handle:
                        handle.emit_artifact(document)

                if emitter:
                    emitter.code(CodePayload(
                        step_id=step_id,
                        phase="done" if exit_code == 0 else "error",
                        language="python",
                        stdout=stdout[-20000:],
                        stderr=stderr[-12000:],
                        exit_code=exit_code,
                        success=exit_code == 0,
                    ))
                if handle:
                    handle.output = f"exit {exit_code}; {len(artifacts)} artifact(s)"
                return (
                    f"Python exited {exit_code}. Generated {len(artifacts)} artifact(s): "
                    f"{', '.join(artifacts) or 'none'}.\nSTDOUT:\n{stdout[-4000:]}\nSTDERR:\n{stderr[-2000:]}"
                )

            if not emitter:
                return _execute(None)
            with emitter.step(
                "supervisor", "tool_call", "Running Python analysis",
                tool_name="run_python", tool_input={"purpose": purpose},
                detail=purpose,
            ) as handle:
                return _execute(handle)

    return StructuredTool.from_function(
        func=_run_python,
        coroutine=_in_thread(_run_python),
        name="run_python",
        description=(
            "Execute short Python analysis code in the server runtime and collect generated "
            "pdf/png/svg/csv/json/html/txt files as artifacts. Use for demo-only charting, "
            "small tabular analysis, or generated reports when SQL/Cypher/vector tools have "
            "already gathered the data. Do not use for database queries; use the dedicated tools."
        ),
    )
