-- Seed default schema definitions, fields, relationships, and app config.

INSERT INTO SchemaDefinition
    (doc_type, version, is_active, description, allowed_file_extensions, max_file_size_mb, created_by)
VALUES
    ('FIR', 1, true, 'First Information Report with case, complainant, victim, accused, and legal sections.', 'txt,html,pdf,docx,png,jpg,jpeg,webp', 15, 'seed'),
    ('IR', 1, true, 'Investigation report narrative and newly observed identifiers.', 'txt,html,pdf,docx,png,jpg,jpeg,webp', 15, 'seed'),
    ('EVIDENCE_BANK_STATEMENT', 1, true, 'Bank statement containing account profile and transaction rows.', 'txt,pdf,docx,png,jpg,jpeg,webp', 15, 'seed'),
    ('EVIDENCE_UPI_SCREENSHOT', 1, true, 'UPI screenshot or export containing payer/payee VPA and amount.', 'html,txt,pdf,png,jpg,jpeg,webp', 15, 'seed'),
    ('EVIDENCE_CHAT_SCREENSHOT', 1, true, 'Chat transcript screenshot/html containing participant numbers and mentioned identifiers.', 'html,txt,pdf,png,jpg,jpeg,webp', 15, 'seed')
ON CONFLICT (doc_type, version) DO NOTHING;

-- Backfill allowed_file_extensions on a DB where this seed already ran under the old,
-- narrower list (ON CONFLICT DO NOTHING above skips existing rows) — safe to re-run.
UPDATE SchemaDefinition SET allowed_file_extensions = 'txt,html,pdf,docx,png,jpg,jpeg,webp' WHERE doc_type IN ('FIR', 'IR');
UPDATE SchemaDefinition SET allowed_file_extensions = 'txt,pdf,docx,png,jpg,jpeg,webp' WHERE doc_type = 'EVIDENCE_BANK_STATEMENT';
UPDATE SchemaDefinition SET allowed_file_extensions = 'html,txt,pdf,png,jpg,jpeg,webp' WHERE doc_type IN ('EVIDENCE_UPI_SCREENSHOT', 'EVIDENCE_CHAT_SCREENSHOT');

-- Ensure only one active version per doc_type.
UPDATE SchemaDefinition sd
SET is_active = (sd.version = latest.max_version)
FROM (
    SELECT doc_type, MAX(version) AS max_version
    FROM SchemaDefinition
    GROUP BY doc_type
) latest
WHERE sd.doc_type = latest.doc_type;

-- -------------------------------------------------------------------------
-- FIR fields
-- -------------------------------------------------------------------------
WITH fir AS (
    SELECT schema_id FROM SchemaDefinition WHERE doc_type = 'FIR' AND is_active = true LIMIT 1
)
INSERT INTO SchemaField
    (schema_id, group_name, is_repeating_group, pole_entity_type, field_name, data_type, is_required,
     target_table, target_column, is_identifier, identifier_type, extraction_hint, display_order)
SELECT fir.schema_id, v.group_name, v.is_repeating_group, v.pole_entity_type, v.field_name, v.data_type, v.is_required,
       v.target_table, v.target_column, v.is_identifier, v.identifier_type, v.extraction_hint, v.display_order
FROM fir,
LATERAL (
    VALUES
      -- CaseMaster
      ('CaseMaster', false, 'Event',  'crime_no',              'string',  true,  'CaseMaster', 'CrimeNo',            false, NULL, 'FIR crime number generated by police station.', 1),
      ('CaseMaster', false, 'Event',  'case_no',               'string',  false, 'CaseMaster', 'CaseNo',             false, NULL, 'Case number (year + running serial).', 2),
      ('CaseMaster', false, 'Event',  'crime_registered_date', 'date',    true,  'CaseMaster', 'CrimeRegisteredDate', false, NULL, 'Date/time FIR was registered.', 3),
      ('CaseMaster', false, 'Event',  'info_received_ps_date', 'date',    false, 'CaseMaster', 'InfoReceivedPSDate', false, NULL, 'Date/time police station received incident information.', 4),
      ('CaseMaster', false, 'Event',  'incident_from_date',    'date',    false, 'CaseMaster', 'IncidentFromDate',   false, NULL, 'Incident start date/time.', 5),
      ('CaseMaster', false, 'Event',  'incident_to_date',      'date',    false, 'CaseMaster', 'IncidentToDate',     false, NULL, 'Incident end date/time.', 6),
      ('CaseMaster', false, 'Event',  'police_station',        'string',  true,  'CaseMaster', 'PoliceStationID',    false, NULL, 'Police station/unit name or id.', 7),
      ('CaseMaster', false, 'Event',  'case_category',         'string',  false, 'CaseMaster', 'CaseCategoryID',     false, NULL, 'Case category (FIR/UDR/PAR etc.).', 8),
      ('CaseMaster', false, 'Event',  'gravity_offence',       'string',  false, 'CaseMaster', 'GravityOffenceID',   false, NULL, 'Gravity class of offence.', 9),
      ('CaseMaster', false, 'Event',  'crime_major_head',      'string',  false, 'CaseMaster', 'CrimeMajorHeadID',   false, NULL, 'Major crime head name/code.', 10),
      ('CaseMaster', false, 'Event',  'crime_minor_head',      'string',  false, 'CaseMaster', 'CrimeMinorHeadID',   false, NULL, 'Minor crime sub-head name/code.', 11),
      ('CaseMaster', false, 'Event',  'case_status',           'string',  false, 'CaseMaster', 'CaseStatusID',       false, NULL, 'Case status label.', 12),
      ('CaseMaster', false, 'Event',  'court',                 'string',  false, 'CaseMaster', 'CourtID',            false, NULL, 'Court where case is being heard.', 13),
      ('CaseMaster', false, 'Event',  'latitude',              'float',   false, 'CaseMaster', 'Latitude',           false, NULL, 'Incident latitude coordinate.', 14),
      ('CaseMaster', false, 'Event',  'longitude',             'float',   false, 'CaseMaster', 'Longitude',          false, NULL, 'Incident longitude coordinate.', 15),
      ('CaseMaster', false, 'Event',  'brief_facts',           'string',  true,  'CaseMaster', 'BriefFacts',         false, NULL, 'Narrative summary of FIR facts.', 16),

      -- ComplainantDetails
      ('ComplainantDetails', true, 'Person', 'complainant_name', 'string', true,  'ComplainantDetails', 'ComplainantName', false, NULL, 'Full complainant name.', 1),
      ('ComplainantDetails', true, 'Person', 'age_year',         'integer', false, 'ComplainantDetails', 'AgeYear',         false, NULL, 'Complainant age in years.', 2),
      ('ComplainantDetails', true, 'Person', 'gender',           'string',  false, 'ComplainantDetails', 'GenderID',        false, NULL, 'Complainant gender label/code.', 3),
      ('ComplainantDetails', true, 'Person', 'occupation',       'string',  false, 'ComplainantDetails', 'OccupationID',    false, NULL, 'Complainant occupation.', 4),
      ('ComplainantDetails', true, 'Person', 'caste',            'string',  false, 'ComplainantDetails', 'CasteID',         false, NULL, 'Complainant caste.', 5),
      ('ComplainantDetails', true, 'Person', 'religion',         'string',  false, 'ComplainantDetails', 'ReligionID',      false, NULL, 'Complainant religion.', 6),
      ('ComplainantDetails', true, 'Person', 'address',          'string',  false, 'ComplainantDetails', 'Address',         false, NULL, 'Complainant address.', 7),

      -- Victim
      ('Victim', true, 'Person', 'victim_name', 'string', false, 'Victim', 'VictimName', false, NULL, 'Victim full name.', 1),
      ('Victim', true, 'Person', 'age_year',    'integer', false, 'Victim', 'AgeYear',    false, NULL, 'Victim age.', 2),
      ('Victim', true, 'Person', 'gender',      'string',  false, 'Victim', 'GenderID',   false, NULL, 'Victim gender.', 3),

      -- Accused
      ('Accused', true, 'Person', 'person_label', 'string', false, 'Accused', 'PersonID',    false, NULL, 'Accused label like A1/A2.', 1),
      ('Accused', true, 'Person', 'accused_name', 'string', false, 'Accused', 'AccusedName', false, NULL, 'Accused full name.', 2),
      ('Accused', true, 'Person', 'age_year',     'integer', false, 'Accused', 'AgeYear',     false, NULL, 'Accused age.', 3),
      ('Accused', true, 'Person', 'gender',       'string',  false, 'Accused', 'GenderID',    false, NULL, 'Accused gender.', 4),

      -- Legal
      ('ActSection', true, NULL, 'act_code',     'string', false, 'ActSectionAssociation', 'ActCode',    false, NULL, 'Legal act code (IPC/ITACT etc.).', 1),
      ('ActSection', true, NULL, 'section_code', 'string', false, 'ActSectionAssociation', 'SectionCode', false, NULL, 'Section code under selected act.', 2),

      -- Mentioned identifiers from FIR narrative
      ('MentionedAccount', true, 'Object', 'account_number', 'string', false, 'Account',    'account_number_raw', true, 'account_number', 'Any mentioned bank account number.', 1),
      ('MentionedUPI',     true, 'Object', 'vpa',            'string', false, 'UPIHandle',  'vpa_raw',            true, 'upi',            'Any mentioned UPI VPA.', 1),
      ('MentionedPhone',   true, 'Object', 'number',         'string', false, 'PhoneNumber','number_raw',         true, 'phone',          'Any mentioned phone number.', 1),
      ('MentionedDevice',  true, 'Object', 'imei',           'string', false, 'Device',     'imei_raw',           true, 'imei',           'Any mentioned IMEI/device id.', 1)
) AS v(
    group_name, is_repeating_group, pole_entity_type, field_name, data_type, is_required,
    target_table, target_column, is_identifier, identifier_type, extraction_hint, display_order
)
ON CONFLICT (schema_id, group_name, field_name) DO NOTHING;

-- -------------------------------------------------------------------------
-- IR fields
-- -------------------------------------------------------------------------
WITH ir AS (
    SELECT schema_id FROM SchemaDefinition WHERE doc_type = 'IR' AND is_active = true LIMIT 1
)
INSERT INTO SchemaField
    (schema_id, group_name, is_repeating_group, pole_entity_type, field_name, data_type, is_required,
     target_table, target_column, is_identifier, identifier_type, extraction_hint, display_order)
SELECT ir.schema_id, v.group_name, v.is_repeating_group, v.pole_entity_type, v.field_name, v.data_type, v.is_required,
       v.target_table, v.target_column, v.is_identifier, v.identifier_type, v.extraction_hint, v.display_order
FROM ir,
LATERAL (
    VALUES
      ('InvestigationReport', false, 'Event', 'report_date',        'date',   false, 'InvestigationReport', 'report_date',        false, NULL, 'Date of investigation report.', 1),
      ('InvestigationReport', false, 'Event', 'findings_narrative', 'string', true,  'InvestigationReport', 'findings_narrative', false, NULL, 'Narrative findings and observations.', 2),
      ('InvestigationReport', false, 'Event', 'status',             'string', false, 'InvestigationReport', 'status',             false, NULL, 'IR status (draft/final).', 3),
      ('InvestigationReport', false, 'Event', 'filed_by',           'string', false, 'InvestigationReport', 'filed_by',           false, NULL, 'Investigating officer ID/name.', 4),

      ('Accused', true, 'Person', 'person_label', 'string', false, 'Accused', 'PersonID',    false, NULL, 'Accused label in IR.', 1),
      ('Accused', true, 'Person', 'accused_name', 'string', false, 'Accused', 'AccusedName', false, NULL, 'Accused full name in IR.', 2),
      ('Accused', true, 'Person', 'age_year',     'integer', false, 'Accused', 'AgeYear',     false, NULL, 'Accused age in IR.', 3),
      ('Accused', true, 'Person', 'gender',       'string',  false, 'Accused', 'GenderID',    false, NULL, 'Accused gender in IR.', 4),

      ('MentionedAccount', true, 'Object', 'account_number', 'string', false, 'Account',    'account_number_raw', true, 'account_number', 'Controller or mule account in IR.', 1),
      ('MentionedUPI',     true, 'Object', 'vpa',            'string', false, 'UPIHandle',  'vpa_raw',            true, 'upi',            'Controller UPI id in IR.', 1),
      ('MentionedPhone',   true, 'Object', 'number',         'string', false, 'PhoneNumber','number_raw',         true, 'phone',          'Phone reference in IR.', 1),
      ('MentionedDevice',  true, 'Object', 'imei',           'string', false, 'Device',     'imei_raw',           true, 'imei',           'Device/IMEI reference in IR.', 1)
) AS v(
    group_name, is_repeating_group, pole_entity_type, field_name, data_type, is_required,
    target_table, target_column, is_identifier, identifier_type, extraction_hint, display_order
)
ON CONFLICT (schema_id, group_name, field_name) DO NOTHING;

-- -------------------------------------------------------------------------
-- EVIDENCE_BANK_STATEMENT fields
-- -------------------------------------------------------------------------
WITH bank AS (
    SELECT schema_id FROM SchemaDefinition WHERE doc_type = 'EVIDENCE_BANK_STATEMENT' AND is_active = true LIMIT 1
)
INSERT INTO SchemaField
    (schema_id, group_name, is_repeating_group, pole_entity_type, field_name, data_type, is_required,
     target_table, target_column, is_identifier, identifier_type, extraction_hint, display_order)
SELECT bank.schema_id, v.group_name, v.is_repeating_group, v.pole_entity_type, v.field_name, v.data_type, v.is_required,
       v.target_table, v.target_column, v.is_identifier, v.identifier_type, v.extraction_hint, v.display_order
FROM bank,
LATERAL (
    VALUES
      ('BankStatement', false, 'Object', 'account_number',      'string', true,  'Account',     'account_number_raw', true, 'account_number', 'Primary account number of statement.', 1),
      ('BankStatement', false, 'Object', 'account_holder_name', 'string', false, 'Account',     'holder_name_raw',    false, NULL,            'Account holder name.', 2),
      ('BankStatement', false, 'Object', 'ifsc',                'string', false, 'Account',     'ifsc',               false, NULL,            'IFSC code.', 3),
      ('BankStatement', false, 'Object', 'bank_name',           'string', false, 'Account',     'bank_name',          false, NULL,            'Bank name.', 4),
      ('BankStatement', false, 'Object', 'branch_name',         'string', false, 'Account',     'branch_name',        false, NULL,            'Branch name.', 5),
      ('BankStatement', false, 'Object', 'branch_district',     'string', false, 'Account',     'branch_district',    false, NULL,            'Branch district.', 6),
      ('BankStatement', false, 'Object', 'account_open_date',   'date',   false, 'Account',     'account_open_date',  false, NULL,            'Account opening date.', 7),

      ('Transaction', true, NULL, 'txn_timestamp',        'date',   false, 'Transaction', 'txn_timestamp', false, NULL,            'Transaction timestamp/date.', 1),
      ('Transaction', true, NULL, 'amount',               'float',  true,  'Transaction', 'amount',        false, NULL,            'Transaction amount.', 2),
      ('Transaction', true, NULL, 'direction',            'string', false, 'Transaction', 'direction',     false, NULL,            'Debit or credit from source account context.', 3),
      ('Transaction', true, NULL, 'mode',                 'string', false, 'Transaction', 'mode',          false, NULL,            'IMPS/UPI/NEFT etc.', 4),
      ('Transaction', true, NULL, 'utr_ref',              'string', false, 'Transaction', 'utr_ref',       false, NULL,            'UTR or transaction reference id.', 5),
      ('Transaction', true, NULL, 'counterparty_account', 'string', false, 'Account',     'account_number_raw', true, 'account_number', 'Counterparty account number.', 6),
      ('Transaction', true, NULL, 'counterparty_upi',     'string', false, 'UPIHandle',   'vpa_raw',           true, 'upi',            'Counterparty UPI id.', 7),
      ('Transaction', true, NULL, 'counterparty_name',    'string', false, 'Account',     'holder_name_raw',    false, NULL,            'Counterparty display/account holder name.', 8)
) AS v(
    group_name, is_repeating_group, pole_entity_type, field_name, data_type, is_required,
    target_table, target_column, is_identifier, identifier_type, extraction_hint, display_order
)
ON CONFLICT (schema_id, group_name, field_name) DO NOTHING;

-- -------------------------------------------------------------------------
-- EVIDENCE_UPI_SCREENSHOT fields
-- -------------------------------------------------------------------------
WITH upi AS (
    SELECT schema_id FROM SchemaDefinition WHERE doc_type = 'EVIDENCE_UPI_SCREENSHOT' AND is_active = true LIMIT 1
)
INSERT INTO SchemaField
    (schema_id, group_name, is_repeating_group, pole_entity_type, field_name, data_type, is_required,
     target_table, target_column, is_identifier, identifier_type, extraction_hint, display_order)
SELECT upi.schema_id, v.group_name, v.is_repeating_group, v.pole_entity_type, v.field_name, v.data_type, v.is_required,
       v.target_table, v.target_column, v.is_identifier, v.identifier_type, v.extraction_hint, v.display_order
FROM upi,
LATERAL (
    VALUES
      ('UPIPayer', false, 'Object', 'payer_vpa',  'string', true,  'UPIHandle', 'vpa_raw',        true,  'upi',  'Payer VPA from screenshot.', 1),
      ('UPIPayer', false, 'Object', 'payer_name', 'string', false, 'UPIHandle', 'holder_name_raw', false, NULL,   'Payer display name from screenshot.', 2),
      ('UPIPayee', false, 'Object', 'payee_vpa',  'string', true,  'UPIHandle', 'vpa_raw',        true,  'upi',  'Payee VPA from screenshot.', 1),
      ('UPIPayee', false, 'Object', 'payee_name', 'string', false, 'UPIHandle', 'holder_name_raw', false, NULL,   'Payee display name from screenshot.', 2),
      ('Transaction', false, NULL,  'amount',        'float',  true,  'Transaction', 'amount',        false, NULL, 'Transaction amount.', 1),
      ('Transaction', false, NULL,  'txn_timestamp', 'date',   false, 'Transaction', 'txn_timestamp', false, NULL, 'Transaction timestamp.', 2),
      ('Transaction', false, NULL,  'utr_ref',       'string', false, 'Transaction', 'utr_ref',       false, NULL, 'UTR / transaction reference.', 3),
      ('Transaction', false, NULL,  'mode',          'string', false, 'Transaction', 'mode',          false, NULL, 'UPI app or channel name.', 4),
      ('Transaction', false, NULL,  'direction',     'string', false, 'Transaction', 'direction',     false, NULL, 'Direction from payer/payee perspective.', 5)
) AS v(
    group_name, is_repeating_group, pole_entity_type, field_name, data_type, is_required,
    target_table, target_column, is_identifier, identifier_type, extraction_hint, display_order
)
ON CONFLICT (schema_id, group_name, field_name) DO NOTHING;

-- -------------------------------------------------------------------------
-- EVIDENCE_CHAT_SCREENSHOT fields
-- -------------------------------------------------------------------------
WITH chat AS (
    SELECT schema_id FROM SchemaDefinition WHERE doc_type = 'EVIDENCE_CHAT_SCREENSHOT' AND is_active = true LIMIT 1
)
INSERT INTO SchemaField
    (schema_id, group_name, is_repeating_group, pole_entity_type, field_name, data_type, is_required,
     target_table, target_column, is_identifier, identifier_type, extraction_hint, display_order)
SELECT chat.schema_id, v.group_name, v.is_repeating_group, v.pole_entity_type, v.field_name, v.data_type, v.is_required,
       v.target_table, v.target_column, v.is_identifier, v.identifier_type, v.extraction_hint, v.display_order
FROM chat,
LATERAL (
    VALUES
      ('ChatParticipant', true, 'Object', 'phone_number', 'string', true,  'PhoneNumber', 'number_raw',      true,  'phone',          'Participant phone number in chat.', 1),
      ('ChatParticipant', true, 'Object', 'display_name', 'string', false, 'PhoneNumber', 'holder_name_raw', false, NULL,             'Participant display name in chat.', 2),
      ('MentionedAccount', true, 'Object', 'account_number', 'string', false, 'Account',   'account_number_raw', true, 'account_number', 'Any bank account mentioned in chat text.', 1),
      ('MentionedUPI',     true, 'Object', 'vpa',            'string', false, 'UPIHandle', 'vpa_raw',            true, 'upi',            'Any UPI VPA mentioned in chat text.', 1)
) AS v(
    group_name, is_repeating_group, pole_entity_type, field_name, data_type, is_required,
    target_table, target_column, is_identifier, identifier_type, extraction_hint, display_order
)
ON CONFLICT (schema_id, group_name, field_name) DO NOTHING;

-- -------------------------------------------------------------------------
-- Seed relationships
-- -------------------------------------------------------------------------
WITH defs AS (
    SELECT schema_id, doc_type FROM SchemaDefinition WHERE is_active = true
)
INSERT INTO SchemaRelationship
    (schema_id, from_group, to_group, relationship_type, direction, fixed_edge_properties, edge_property_source_fields)
SELECT d.schema_id, r.from_group, r.to_group, r.relationship_type, r.direction, r.fixed_edge_properties::jsonb, r.edge_fields
FROM defs d
JOIN (
    VALUES
      ('FIR', 'CaseMaster', 'Accused',            'INVOLVES',       'from_to', '{"role":"accused"}', NULL),
      ('FIR', 'CaseMaster', 'Victim',             'INVOLVES',       'from_to', '{"role":"victim"}', NULL),
      ('FIR', 'CaseMaster', 'ComplainantDetails', 'INVOLVES',       'from_to', '{"role":"complainant"}', NULL),
      ('FIR', 'CaseMaster', 'MentionedAccount',   'MENTIONS',       'from_to', '{}', NULL),
      ('FIR', 'CaseMaster', 'MentionedUPI',       'MENTIONS',       'from_to', '{}', NULL),
      ('FIR', 'CaseMaster', 'MentionedPhone',     'MENTIONS',       'from_to', '{}', NULL),
      ('FIR', 'CaseMaster', 'MentionedDevice',    'MENTIONS',       'from_to', '{}', NULL),

      ('IR', 'CaseMaster', 'InvestigationReport', 'HAS_EVIDENCE',   'from_to', '{}', NULL),
      ('IR', 'Accused',    'MentionedAccount',    'OWNS',           'from_to', '{}', NULL),
      ('IR', 'Accused',    'MentionedUPI',        'OWNS',           'from_to', '{}', NULL),
      ('IR', 'Accused',    'MentionedPhone',      'OWNS',           'from_to', '{}', NULL),
      ('IR', 'Accused',    'MentionedDevice',     'OWNS',           'from_to', '{}', NULL),
      ('IR', 'CaseMaster', 'MentionedAccount',    'MENTIONS',       'from_to', '{}', NULL),
      ('IR', 'CaseMaster', 'MentionedUPI',        'MENTIONS',       'from_to', '{}', NULL),
      ('IR', 'CaseMaster', 'MentionedPhone',      'MENTIONS',       'from_to', '{}', NULL),
      ('IR', 'CaseMaster', 'MentionedDevice',     'MENTIONS',       'from_to', '{}', NULL),

      -- Evidence-node model (Section 8): CaseMaster -HAS_EVIDENCE-> Evidence -MENTIONS-> Object.
      -- "Evidence" is a structural group (one node per evidence upload, from the Evidence SQL
      -- row) rather than an LLM-extracted SchemaField group; the pipeline always makes it
      -- available at runtime for every EVIDENCE_* doc_type, so no SchemaField rows are needed for it.
      ('EVIDENCE_BANK_STATEMENT', 'CaseMaster',   'Evidence',       'HAS_EVIDENCE',   'from_to', '{}', NULL),
      ('EVIDENCE_BANK_STATEMENT', 'Evidence',     'BankStatement',  'MENTIONS',       'from_to', '{}', NULL),
      ('EVIDENCE_BANK_STATEMENT', 'Transaction',  'Transaction',    'TRANSACTED_WITH', 'from_to', '{}', 'amount,txn_timestamp'),

      ('EVIDENCE_UPI_SCREENSHOT', 'CaseMaster',   'Evidence',       'HAS_EVIDENCE',   'from_to', '{}', NULL),
      ('EVIDENCE_UPI_SCREENSHOT', 'Evidence',     'UPIPayer',       'MENTIONS',       'from_to', '{}', NULL),
      ('EVIDENCE_UPI_SCREENSHOT', 'Evidence',     'UPIPayee',       'MENTIONS',       'from_to', '{}', NULL),
      ('EVIDENCE_UPI_SCREENSHOT', 'UPIPayer',     'UPIPayee',       'TRANSACTED_WITH', 'from_to', '{}', 'amount,txn_timestamp,utr_ref'),

      ('EVIDENCE_CHAT_SCREENSHOT', 'CaseMaster',  'Evidence',        'HAS_EVIDENCE',  'from_to', '{}', NULL),
      ('EVIDENCE_CHAT_SCREENSHOT', 'Evidence',    'ChatParticipant', 'MENTIONS',      'from_to', '{}', NULL),
      ('EVIDENCE_CHAT_SCREENSHOT', 'ChatParticipant', 'MentionedAccount', 'MENTIONS', 'from_to', '{}', NULL),
      ('EVIDENCE_CHAT_SCREENSHOT', 'ChatParticipant', 'MentionedUPI', 'MENTIONS', 'from_to', '{}', NULL)
) AS r(doc_type, from_group, to_group, relationship_type, direction, fixed_edge_properties, edge_fields)
  ON d.doc_type = r.doc_type
ON CONFLICT (schema_id, from_group, to_group, relationship_type) DO NOTHING;

INSERT INTO AppConfig(config_key, config_value, updated_by)
VALUES ('entity_review_threshold', '0.80', 'seed')
ON CONFLICT (config_key) DO NOTHING;

