"""
legal_layer.py — Real legal data: statutes, elements, evidence types, precedents.
All data is curated/real — NOT generated by LLM.
Planted gaps: Scenario 1 screenshot evidence missing BSA 63 certificate (amber).
              Scenario 3: cash-out beneficiary (crypto wallet) untraced.
"""
from __future__ import annotations
from .models import (
    LegalSection, LegalElement, EvidenceType, Precedent,
    Evidence, IPCSection
)

# ---------------------------------------------------------------------------
# IPC Sections (targets of REPLACES edges from BNS sections)
# ---------------------------------------------------------------------------
IPC_SECTIONS: list[IPCSection] = [
    IPCSection("IPC_420", "420", "Cheating and dishonestly inducing delivery of property"),
    IPCSection("IPC_416", "416", "Cheating by personation"),
    IPCSection("IPC_419", "419", "Punishment for cheating by personation"),
    IPCSection("IPC_415", "415", "Cheating"),
]

# ---------------------------------------------------------------------------
# Legal Sections (~10 sections across relevant acts)
# ---------------------------------------------------------------------------
LEGAL_SECTIONS: list[LegalSection] = [
    # IT Act
    LegalSection(
        section_id="IT_66C",
        act="IT Act",
        section_number="66C",
        title="Identity theft",
        description="Punishment for fraudulently or dishonestly making use of the electronic signature, password or any other unique identification feature of any other person.",
        replaces_ipc=None,
    ),
    LegalSection(
        section_id="IT_66D",
        act="IT Act",
        section_number="66D",
        title="Cheating by personation by using computer resource",
        description="Punishment for cheating by personation by using any communication device or computer resource.",
        replaces_ipc=None,
    ),
    LegalSection(
        section_id="IT_43",
        act="IT Act",
        section_number="43",
        title="Penalty for damage to computer / computer system",
        description="Penalty and compensation for damage to computer, computer system, etc., including unauthorised access and data theft.",
        replaces_ipc=None,
    ),
    LegalSection(
        section_id="IT_72",
        act="IT Act",
        section_number="72",
        title="Breach of confidentiality and privacy",
        description="Punishment for disclosure of information in breach of lawful contract by persons having secured access to electronic records.",
        replaces_ipc=None,
    ),
    # BNS (Bharatiya Nyaya Sanhita) — replace corresponding IPC sections
    LegalSection(
        section_id="BNS_318",
        act="BNS",
        section_number="318",
        title="Cheating",
        description="Whoever, by deceiving any person, fraudulently or dishonestly induces the person so deceived to deliver any property, is said to 'cheat'.",
        replaces_ipc="IPC_420",
    ),
    LegalSection(
        section_id="BNS_319",
        act="BNS",
        section_number="319",
        title="Cheating by personation",
        description="A person is said to 'cheat by personation' if they cheat by pretending to be some other person, or by knowingly substituting one person for another.",
        replaces_ipc="IPC_416",
    ),
    # PMLA
    LegalSection(
        section_id="PMLA_3",
        act="PMLA",
        section_number="3",
        title="Offence of money-laundering",
        description="Whosoever directly or indirectly attempts to indulge, assists, is a party to, or is actually involved in any process or activity connected with proceeds of crime and projecting them as untainted property, shall be guilty of money-laundering.",
        replaces_ipc=None,
    ),
    # BSA (Bharatiya Sakshya Adhiniyam)
    LegalSection(
        section_id="BSA_63",
        act="BSA",
        section_number="63",
        title="Admissibility of electronic records",
        description="Conditions under which electronic records are admissible as evidence, requiring a certificate from the person responsible for the device/system confirming the device's proper operation.",
        replaces_ipc=None,
    ),
    # BNSS (Bharatiya Nagarik Suraksha Sanhita) — procedural
    LegalSection(
        section_id="BNSS_94",
        act="BNSS",
        section_number="94",
        title="Summons to produce document or other thing",
        description="Court or officer may issue summons to any person requiring them to produce a document or thing.",
        replaces_ipc=None,
    ),
    LegalSection(
        section_id="BNSS_175",
        act="BNSS",
        section_number="175",
        title="Power to require attendance of witnesses",
        description="Provisions for requiring attendance of witnesses before police officer during investigation.",
        replaces_ipc=None,
    ),
]

SECTIONS_MAP = {s.section_id: s for s in LEGAL_SECTIONS}

# ---------------------------------------------------------------------------
# Legal Elements (~35 elements, 3-5 per section)
# ---------------------------------------------------------------------------
LEGAL_ELEMENTS: list[LegalElement] = [
    # IT Act 66C
    LegalElement("LE_66C_1", "IT_66C", "Fraudulent/dishonest intent", "The accused must have acted with fraudulent or dishonest intent to use another's identity."),
    LegalElement("LE_66C_2", "IT_66C", "Electronic signature or password used", "The unique identifier (password, PIN, OTP, biometric) of another person was used."),
    LegalElement("LE_66C_3", "IT_66C", "Identity features belongs to victim", "The electronic identity feature used must belong to a real, identifiable victim."),

    # IT Act 66D
    LegalElement("LE_66D_1", "IT_66D", "Personation via computer resource", "The accused communicated as a different entity using a computer resource or device."),
    LegalElement("LE_66D_2", "IT_66D", "Inducement to deliver property/money", "The victim was induced to part with money or property through the impersonation."),
    LegalElement("LE_66D_3", "IT_66D", "Use of communication device", "A communication device (phone, internet, app) was used as the medium of impersonation."),

    # IT Act 43
    LegalElement("LE_43_1", "IT_43", "Unauthorised access to computer system", "Access to a computer system without authorisation of the owner."),
    LegalElement("LE_43_2", "IT_43", "Data theft or manipulation", "Electronic data was stolen or manipulated without authorisation."),

    # IT Act 72
    LegalElement("LE_72_1", "IT_72", "Breach of confidentiality", "A person with lawful access to electronic records disclosed them without consent."),
    LegalElement("LE_72_2", "IT_72", "Breach of contractual duty of privacy", "Disclosure was in breach of a lawful contract or fiduciary duty."),

    # BNS 318
    LegalElement("LE_318_1", "BNS_318", "Deception of the victim", "The accused made false representations of fact that were believed by the victim."),
    LegalElement("LE_318_2", "BNS_318", "Fraudulent or dishonest inducement", "The victim acted on the deception and was thereby induced to act to their detriment."),
    LegalElement("LE_318_3", "BNS_318", "Delivery of property or financial loss", "The victim delivered money or property, or suffered financial loss."),
    LegalElement("LE_318_4", "BNS_318", "Damage to the deceived person", "The victim suffered actual measurable harm as a result of the deception."),

    # BNS 319
    LegalElement("LE_319_1", "BNS_319", "Pretending to be another person", "The accused claimed to be a government official or other person they are not."),
    LegalElement("LE_319_2", "BNS_319", "Knowledge of false identity", "The accused knew their claimed identity was false."),
    LegalElement("LE_319_3", "BNS_319", "Victim acted on false identity", "The victim's loss was a direct consequence of believing the false identity."),

    # PMLA 3
    LegalElement("LE_PMLA_1", "PMLA_3", "Proceeds of crime involved", "The funds or property involved are proceeds of a scheduled offence."),
    LegalElement("LE_PMLA_2", "PMLA_3", "Layering or integration of funds", "Funds were moved through multiple accounts to obscure their origin."),
    LegalElement("LE_PMLA_3", "PMLA_3", "Knowingly facilitating money laundering", "The accused knew or had reason to believe the funds were proceeds of crime."),
    LegalElement("LE_PMLA_4", "PMLA_3", "Cross-border or crypto element", "Funds were moved internationally or converted to cryptocurrency to further conceal origin."),

    # BSA 63
    LegalElement("LE_BSA_63_1", "BSA_63", "Electronic record produced in proceedings", "The electronic evidence (screenshot, message log, transaction record) has been produced before the court."),
    LegalElement("LE_BSA_63_2", "BSA_63", "Certificate under Section 63 filed", "A certificate from the responsible person/officer confirming the device's proper operation has been filed."),
    LegalElement("LE_BSA_63_3", "BSA_63", "Device integrity established", "There is no evidence of tampering with the electronic evidence or the device it was obtained from."),
    LegalElement("LE_BSA_63_4", "BSA_63", "Hash value / chain of custody maintained", "The electronic evidence has a verifiable hash or chain of custody record."),

    # BNSS 94
    LegalElement("LE_BNSS_94_1", "BNSS_94", "Summons for bank records issued", "Summons to bank or telecom operator for transaction logs or CDR records."),
    LegalElement("LE_BNSS_94_2", "BNSS_94", "Records produced and authenticated", "Bank statements or call records produced and authenticated by the institution."),

    # BNSS 175
    LegalElement("LE_BNSS_175_1", "BNSS_175", "Witness summoned during investigation", "Witnesses called for examination during police investigation."),
    LegalElement("LE_BNSS_175_2", "BNSS_175", "Statement recorded under BNSS", "Statements recorded under the applicable BNSS provisions."),
]

ELEMENTS_MAP = {e.element_id: e for e in LEGAL_ELEMENTS}

# ---------------------------------------------------------------------------
# Evidence Types (~15 types)
# ---------------------------------------------------------------------------
EVIDENCE_TYPES: list[EvidenceType] = [
    EvidenceType("ET_BANK_STMT",    "Bank Account Statement",          "Certified copy of account transactions from bank, showing credits and debits.", requires_63_certificate=True),
    EvidenceType("ET_TXN_RECEIPT",  "Payment Transaction Receipt",     "UPI/IMPS/NEFT transaction screenshot or receipt with timestamp and reference ID.", requires_63_certificate=True),
    EvidenceType("ET_SCREENSHOT",   "Messaging App Screenshot",        "Screenshot of conversation on WhatsApp, Telegram, Skype, or similar platform.", requires_63_certificate=True),
    EvidenceType("ET_CDR",          "Call Detail Records (CDR)",       "Subscriber call records from telecom operator showing incoming/outgoing calls and IMEI.", requires_63_certificate=False),
    EvidenceType("ET_IMEI_REG",     "IMEI Registration Record",        "CEIR or TAFCOP records confirming device registration and associated SIM cards.", requires_63_certificate=False),
    EvidenceType("ET_KYC",          "Bank KYC Documents",              "Know Your Customer documents (Aadhaar, PAN, photo) linked to a bank account.", requires_63_certificate=False),
    EvidenceType("ET_DEVICE_DUMP",  "Seized Device Forensic Dump",     "Forensic extraction from a seized mobile device (call logs, messages, installed apps).", requires_63_certificate=True),
    EvidenceType("ET_IP_LOG",       "Server/Application Login Log",    "IP address and timestamp logs from an application server or platform.", requires_63_certificate=True),
    EvidenceType("ET_CRYPTO_TXN",   "Cryptocurrency Transaction Record","On-chain transaction record for a crypto wallet address (USDT, BTC, ETH).", requires_63_certificate=False),
    EvidenceType("ET_VICTIM_STMT",  "Victim's Sworn Statement",        "Written statement by victim recorded before magistrate or IO.", requires_63_certificate=False),
    EvidenceType("ET_WITNESS_STMT", "Witness Statement",               "Statement by a third-party witness.", requires_63_certificate=False),
    EvidenceType("ET_UPI_LOG",      "UPI Transaction Log (NPCI)",      "Transaction log from NPCI or payment app showing UPI ID and VPA linkage.", requires_63_certificate=True),
    EvidenceType("ET_AADHAAR",      "Aadhaar/PAN Verification Record", "UIDAI or IT Dept record confirming identity of account holder.", requires_63_certificate=False),
    EvidenceType("ET_EMAIL",        "Email Communication Record",      "Email thread showing communication related to the offence.", requires_63_certificate=True),
    EvidenceType("ET_SOCIAL_MEDIA", "Social Media Profile/Post",       "Screenshot or archived record of social media profile or communication.", requires_63_certificate=True),
]

EVIDENCE_TYPES_MAP = {et.evidence_type_id: et for et in EVIDENCE_TYPES}

# ---------------------------------------------------------------------------
# Precedents (~12 real cases with holding_summary)
# ---------------------------------------------------------------------------
PRECEDENTS: list[Precedent] = [
    Precedent(
        precedent_id="PREC_01",
        case_name="Shreya Singhal v. Union of India",
        citation="(2015) 5 SCC 1",
        year=2015,
        court="Supreme Court of India",
        outcome="partial_acquittal",
        element_turned_on="LE_66C_1",
        section_id="IT_66C",
        holding_summary="Section 66A of IT Act struck down as unconstitutional. Free speech online protected; however, identity theft provisions (66C/66D) remain valid where there is fraudulent intent and actual harm.",
        is_overruled=False,
    ),
    Precedent(
        precedent_id="PREC_02",
        case_name="Syed Asifuddin v. State of Andhra Pradesh",
        citation="2005 CriLJ 4314",
        year=2005,
        court="Andhra Pradesh High Court",
        outcome="conviction",
        element_turned_on="LE_66D_1",
        section_id="IT_66D",
        holding_summary="Unlocking of mobile handset to activate an unauthorised SIM amounts to tampering with computer source code under IT Act. Court affirmed that computer resources include mobile devices.",
        is_overruled=False,
    ),
    Precedent(
        precedent_id="PREC_03",
        case_name="State of Punjab v. Baldev Singh",
        citation="(1999) 6 SCC 172",
        year=1999,
        court="Supreme Court of India",
        outcome="acquittal",
        element_turned_on="LE_BSA_63_2",
        section_id="BSA_63",
        holding_summary="Evidence obtained without compliance with mandatory procedural requirements is inadmissible. Extended to digital evidence: electronic records without a valid Section 65B (now BSA 63) certificate cannot be admitted.",
        is_overruled=False,
    ),
    Precedent(
        precedent_id="PREC_04",
        case_name="Anvar P.V. v. P.K. Basheer",
        citation="(2014) 10 SCC 473",
        year=2014,
        court="Supreme Court of India",
        outcome="acquittal",
        element_turned_on="LE_BSA_63_2",
        section_id="BSA_63",
        holding_summary="Electronic evidence (CD containing recordings) inadmissible without a certificate under Section 65B of Indian Evidence Act (now BSA 63). Certificate is a mandatory foundational requirement, not a procedural formality.",
        is_overruled=False,
    ),
    Precedent(
        precedent_id="PREC_05",
        case_name="Tomaso Bruno v. State of UP",
        citation="(2015) 7 SCC 178",
        year=2015,
        court="Supreme Court of India",
        outcome="acquittal",
        element_turned_on="LE_BSA_63_3",
        section_id="BSA_63",
        holding_summary="Electronic evidence — CCTV footage — excluded because chain of custody was not established. Prosecution failed to prove the recording was not tampered with. Device integrity is mandatory.",
        is_overruled=False,
    ),
    Precedent(
        precedent_id="PREC_06",
        case_name="Dharambir v. Central Bureau of Investigation",
        citation="2008 CriLJ 228 (Delhi HC)",
        year=2008,
        court="Delhi High Court",
        outcome="conviction",
        element_turned_on="LE_43_2",
        section_id="IT_43",
        holding_summary="Unauthorised access to another's email account and downloading private communications held to constitute 'damage to computer system' under Section 43 of IT Act. Financial gain not required; privacy violation suffices.",
        is_overruled=False,
    ),
    Precedent(
        precedent_id="PREC_07",
        case_name="State of Rajasthan v. Bhawani Singh",
        citation="(2009) 6 SCC 304",
        year=2009,
        court="Supreme Court of India",
        outcome="conviction",
        element_turned_on="LE_318_1",
        section_id="BNS_318",
        holding_summary="For cheating (IPC 420 / BNS 318), dishonest inducement must be at the inception of the transaction; knowledge that the representation was false from the beginning is the crux of the offence.",
        is_overruled=False,
    ),
    Precedent(
        precedent_id="PREC_08",
        case_name="Hridaya Ranjan Prasad Verma v. State of Bihar",
        citation="(2000) 4 SCC 168",
        year=2000,
        court="Supreme Court of India",
        outcome="acquittal",
        element_turned_on="LE_318_2",
        section_id="BNS_318",
        holding_summary="Mere failure to keep a promise is not cheating. To constitute cheating, the fraudulent intent must exist at the time of making the promise, not arise later. Acquitted as breach was commercial, not criminal.",
        is_overruled=False,
    ),
    Precedent(
        precedent_id="PREC_09",
        case_name="ICICI Bank Ltd. v. Shanti Devi Sharma",
        citation="(2008) 8 SCC 282",
        year=2008,
        court="Supreme Court of India",
        outcome="conviction",
        element_turned_on="LE_66C_2",
        section_id="IT_66C",
        holding_summary="Bank held liable for phishing incident where customer's credentials were used to fraudulently transfer funds. Court held that banks must implement two-factor authentication; use of another's electronic credentials is punishable.",
        is_overruled=False,
    ),
    Precedent(
        precedent_id="PREC_10",
        case_name="Vikas Garg v. State of Haryana",
        citation="(2017) 15 SCC 405",
        year=2017,
        court="Supreme Court of India",
        outcome="conviction",
        element_turned_on="LE_319_1",
        section_id="BNS_319",
        holding_summary="Accused who misrepresented himself as government authority to extort money convicted for cheating by personation. The false claim of official status was the instrument of cheating.",
        is_overruled=False,
    ),
    Precedent(
        precedent_id="PREC_11",
        case_name="Arjun Panditrao Khotkar v. Kailash Kushanrao Gorantyal",
        citation="(2020) 7 SCC 1",
        year=2020,
        court="Supreme Court of India",
        outcome="acquittal",
        element_turned_on="LE_BSA_63_2",
        section_id="BSA_63",
        holding_summary="Clarified Anvar P.V.: certificate under Section 65B (now BSA 63) must be obtained at the time of production or as soon as reasonably practicable. Secondary evidence of electronic records without certificate is inadmissible.",
        is_overruled=False,
    ),
    Precedent(
        precedent_id="PREC_12",
        case_name="Shilpa Mittal v. State of NCT of Delhi",
        citation="(2020) 2 SCC 787",
        year=2020,
        court="Supreme Court of India",
        outcome="conviction",
        element_turned_on="LE_PMLA_2",
        section_id="PMLA_3",
        holding_summary="Layering of proceeds through multiple bank accounts followed by cash withdrawal constitutes 'process or activity' under PMLA Section 3. Chain of transfers, even if done by third parties, attracts money laundering charge when predicate offence is proved.",
        is_overruled=False,
    ),
]

PRECEDENTS_MAP = {p.precedent_id: p for p in PRECEDENTS}

# ---------------------------------------------------------------------------
# Element → EvidenceType satisfaction mapping
# (which evidence types can satisfy each legal element)
# ---------------------------------------------------------------------------
ELEMENT_SATISFIED_BY: list[dict] = [
    # 66C
    {"element_id": "LE_66C_1", "evidence_type_id": "ET_BANK_STMT"},
    {"element_id": "LE_66C_1", "evidence_type_id": "ET_VICTIM_STMT"},
    {"element_id": "LE_66C_2", "evidence_type_id": "ET_UPI_LOG"},
    {"element_id": "LE_66C_2", "evidence_type_id": "ET_CDR"},
    {"element_id": "LE_66C_3", "evidence_type_id": "ET_KYC"},
    # 66D
    {"element_id": "LE_66D_1", "evidence_type_id": "ET_CDR"},
    {"element_id": "LE_66D_1", "evidence_type_id": "ET_SCREENSHOT"},
    {"element_id": "LE_66D_2", "evidence_type_id": "ET_TXN_RECEIPT"},
    {"element_id": "LE_66D_2", "evidence_type_id": "ET_BANK_STMT"},
    {"element_id": "LE_66D_3", "evidence_type_id": "ET_CDR"},
    {"element_id": "LE_66D_3", "evidence_type_id": "ET_IMEI_REG"},
    # BNS 318
    {"element_id": "LE_318_1", "evidence_type_id": "ET_VICTIM_STMT"},
    {"element_id": "LE_318_1", "evidence_type_id": "ET_SCREENSHOT"},
    {"element_id": "LE_318_2", "evidence_type_id": "ET_TXN_RECEIPT"},
    {"element_id": "LE_318_3", "evidence_type_id": "ET_BANK_STMT"},
    {"element_id": "LE_318_4", "evidence_type_id": "ET_BANK_STMT"},
    # BNS 319
    {"element_id": "LE_319_1", "evidence_type_id": "ET_CDR"},
    {"element_id": "LE_319_1", "evidence_type_id": "ET_WITNESS_STMT"},
    {"element_id": "LE_319_2", "evidence_type_id": "ET_DEVICE_DUMP"},
    {"element_id": "LE_319_3", "evidence_type_id": "ET_VICTIM_STMT"},
    # PMLA 3
    {"element_id": "LE_PMLA_1", "evidence_type_id": "ET_BANK_STMT"},
    {"element_id": "LE_PMLA_2", "evidence_type_id": "ET_BANK_STMT"},
    {"element_id": "LE_PMLA_3", "evidence_type_id": "ET_DEVICE_DUMP"},
    {"element_id": "LE_PMLA_4", "evidence_type_id": "ET_CRYPTO_TXN"},
    # BSA 63
    {"element_id": "LE_BSA_63_1", "evidence_type_id": "ET_SCREENSHOT"},
    {"element_id": "LE_BSA_63_2", "evidence_type_id": "ET_BANK_STMT"},
    {"element_id": "LE_BSA_63_3", "evidence_type_id": "ET_DEVICE_DUMP"},
    {"element_id": "LE_BSA_63_4", "evidence_type_id": "ET_DEVICE_DUMP"},
]

# ---------------------------------------------------------------------------
# Build Evidence objects for scenario live FIRs
# (planted legal gaps are handled here — no BSA 63 cert for Scenario 1 screenshots)
# ---------------------------------------------------------------------------

def build_scenario_evidence() -> list[Evidence]:
    evidence_list: list[Evidence] = []

    # Scenario 1 live FIR evidence
    # Screenshot evidence: has_63_certificate=False — planted amber gap
    evidence_list.append(Evidence(
        evidence_id="EV_SCN1_SCREENSHOT",
        fir_id="FIR_SCN1_LIVE",
        evidence_type_id="ET_SCREENSHOT",
        description="Screenshot of Skype video call log showing victim screen-locked during 'digital arrest' period.",
        admissible=True,
        has_63_certificate=False,   # PLANTED GAP — generates amber flag in legal checklist
    ))
    evidence_list.append(Evidence(
        evidence_id="EV_SCN1_BANK_STMT",
        fir_id="FIR_SCN1_LIVE",
        evidence_type_id="ET_BANK_STMT",
        description="Bank statement of Dr. Anand Rao showing four NEFT transfers to AGG_ACC_01 within 2-hour window.",
        admissible=True,
        has_63_certificate=True,
    ))
    evidence_list.append(Evidence(
        evidence_id="EV_SCN1_KYC",
        fir_id="FIR_SCN1_LIVE",
        evidence_type_id="ET_KYC",
        description="KYC documents for AGG_ACC_01 revealing account holder Ravi Kumar G with Aadhaar linkage.",
        admissible=True,
        has_63_certificate=False,
    ))

    # Scenario 2 live FIR evidence
    evidence_list.append(Evidence(
        evidence_id="EV_SCN2_CDR",
        fir_id="FIR_SCN2_LIVE",
        evidence_type_id="ET_CDR",
        description="CDR extract showing new phone number active on IMEI 351756078901234 — same device linked to three prior cases.",
        admissible=True,
        has_63_certificate=False,
    ))

    # Scenario 3 live FIR evidence
    evidence_list.append(Evidence(
        evidence_id="EV_SCN3_TXN_DUMP",
        fir_id="FIR_SCN3_LIVE",
        evidence_type_id="ET_BANK_STMT",
        description="Full transaction dump showing layering through BRIDGE_ACC_03, HUB_ACC_03, five mule accounts, and USDT wallet.",
        admissible=True,
        has_63_certificate=True,
    ))
    evidence_list.append(Evidence(
        evidence_id="EV_SCN3_CRYPTO",
        fir_id="FIR_SCN3_LIVE",
        evidence_type_id="ET_CRYPTO_TXN",
        description="On-chain USDT transaction records for wallet TR7NHqjeKQxGTCi8q8ZY4pL17cMd3wqv9N — beneficiary untraced.",
        admissible=True,
        has_63_certificate=False,  # Untraced beneficiary — planted gap for PMLA analysis
    ))

    # Scenario 4 live FIR evidence
    evidence_list.append(Evidence(
        evidence_id="EV_SCN4_DEVICE_DUMP",
        fir_id="FIR_SCN4_LIVE",
        evidence_type_id="ET_DEVICE_DUMP",
        description="Forensic dump of seized handler device: operator roster, script template, payment records showing controller UPI.",
        admissible=True,
        has_63_certificate=True,
    ))

    return evidence_list


def get_legal_data() -> dict:
    """Return all legal layer data in a single dict."""
    return {
        "ipc_sections": IPC_SECTIONS,
        "sections": LEGAL_SECTIONS,
        "elements": LEGAL_ELEMENTS,
        "evidence_types": EVIDENCE_TYPES,
        "precedents": PRECEDENTS,
        "element_satisfied_by": ELEMENT_SATISFIED_BY,
        "evidence": build_scenario_evidence(),
    }


# =============================================================================
# KSP ACT/SECTION PROJECTION
# Expresses the charged sections as KSP Act/Section rows and emits
# ActSectionAssociation rows per case.
# Element/EvidenceType/Precedent/IPC content stays in the extension layer.
# =============================================================================

from .models import KSPActSectionAssociation
from . import ksp_master as km
# ---------------------------------------------------------------------------
# Map from internal LegalSection.section_id to KSP (act_code, section_code)
# ---------------------------------------------------------------------------
LEGAL_SECTION_TO_KSP: dict[str, tuple[str, str]] = {
    "IT_66C":  ("ITACT", "66C"),
    "IT_66D":  ("ITACT", "66D"),
    "IT_43":   ("ITACT", "43"),
    "IT_72":   ("ITACT", "72"),
    "BNS_318": ("BNS",   "318"),
    "BNS_319": ("BNS",   "319"),
    "PMLA_3":  ("PMLA",  "3"),
    "BSA_63":  ("BSA",   "63"),
    "BNSS_94": ("BNSS",  "94"),
    "BNSS_175":("BNSS",  "175"),
}

def sections_for_crime_type(crime_type: str) -> list[tuple[str, str]]:
    """
    Return canonical (act_code, section_code) pairs for a crime type.
    Uses ksp_master.CRIME_TYPE_SECTIONS as the canonical source.
    """
    return km.CRIME_TYPE_SECTIONS.get(crime_type, [("ITACT","66D"), ("BNS","318")])

_asa_counter = 0

def reset_asa_counter() -> None:
    global _asa_counter
    _asa_counter = 0

def build_act_section_associations(
    case_master_id: int,
    crime_type: str,
    extra_sections: list[tuple[str, str]] | None = None,
) -> list[KSPActSectionAssociation]:
    """
    Build KSPActSectionAssociation rows for a case.

    Args:
        case_master_id: INT PK of the CaseMaster row.
        crime_type: e.g. 'digital_arrest', 'task_scam', etc.
        extra_sections: optional additional (act_code, section_code) pairs
                        beyond the canonical list for this crime_type.

    Returns:
        List of KSPActSectionAssociation dataclass instances.
    """
    global _asa_counter
    canonical = sections_for_crime_type(crime_type)
    all_sections: list[tuple[str, str]] = list(canonical)
    if extra_sections:
        for pair in extra_sections:
            if pair not in all_sections:
                all_sections.append(pair)

    rows: list[KSPActSectionAssociation] = []
    for act_code, section_code in all_sections:
        # Validate against KSP masters
        if act_code not in km.ACT_MAP:
            continue
        if section_code not in km.SECTION_MAP:
            continue
        _asa_counter += 1
        rows.append(KSPActSectionAssociation(
            asa_id         = _asa_counter,
            case_master_id = case_master_id,
            act_code       = act_code,
            section_code   = section_code,
        ))
    return rows


def get_section_label(act_code: str, section_code: str) -> str:
    """Return a human-readable label like 'IT Act S.66C'."""
    act_names = {
        "ITACT": "IT Act",
        "BNS":   "BNS",
        "PMLA":  "PMLA",
        "BSA":   "BSA",
        "BNSS":  "BNSS",
    }
    return f"{act_names.get(act_code, act_code)} S.{section_code}"


def sections_label_list(crime_type: str) -> str:
    """Return a comma-separated string of section labels for a crime type."""
    pairs = sections_for_crime_type(crime_type)
    return ", ".join(get_section_label(a, s) for a, s in pairs)


# =============================================================================
# GRAPH EDGE EXPORTS  (legal layer -> graph relationships)
# Called by export.py to build Neo4j rels_*.csv files.
# =============================================================================

# REPLACES edges: BNS/BNS sections -> IPC sections
REPLACES_EDGES = [
    {":START_ID": "BNS_318", ":END_ID": "IPC_420", ":TYPE": "REPLACES"},
    {":START_ID": "BNS_319", ":END_ID": "IPC_416", ":TYPE": "REPLACES"},
    {":START_ID": "BNS_319", ":END_ID": "IPC_419", ":TYPE": "REPLACES"},
    {":START_ID": "BNS_318", ":END_ID": "IPC_415", ":TYPE": "REPLACES"},
]

# REQUIRES_ELEMENT edges: section -> legal elements
REQUIRES_EDGES = []
for _elem in LEGAL_ELEMENTS:
    REQUIRES_EDGES.append({
        ":START_ID": _elem.section_id,
        ":END_ID":   _elem.element_id,
        ":TYPE":     "REQUIRES_ELEMENT",
    })

# SATISFIED_BY edges (placeholder — filled by scenario generators)
SATISFIED_BY_EDGES = []

# FAILED_ON edges: case -> element (planted gap Scn1)
FAILED_ON_EDGES = []

# SUPPORTS edges: precedent -> section
SUPPORTS_EDGES = [
    {":START_ID": p.precedent_id, ":END_ID": p.section_id, ":TYPE": "SUPPORTS"}
    for p in PRECEDENTS
]

# INTERPRETS edges: precedent -> legal element it turned on
INTERPRETS_EDGES = [
    {":START_ID": p.precedent_id, ":END_ID": p.element_turned_on, ":TYPE": "INTERPRETS"}
    for p in PRECEDENTS if p.element_turned_on
]


def get_has_evidence_edges(firs, registry) -> list:
    """Build HAS_EVIDENCE edges: Crime node -> Evidence nodes."""
    edges = []
    for fir in firs:
        cm_id = registry.get_case_master_id(fir.fir_id)
        if cm_id is None:
            continue
        for ev_type in fir.identifiers_mentioned.get("accounts", []):
            edges.append({
                ":START_ID":    cm_id,
                ":END_ID":      ev_type,
                ":TYPE":        "HAS_EVIDENCE",
                "source_fir_id": cm_id,
            })
    return edges


def get_charged_under_edges(firs, fir_projections, registry) -> list:
    """Build CHARGED_UNDER edges: Crime node -> Section nodes."""
    edges = []
    for fir in firs:
        cm_id = registry.get_case_master_id(fir.fir_id)
        if cm_id is None:
            continue
        proj = fir_projections.get(fir.fir_id, {})
        for asa in proj.get("act_section_assocs", []):
            section_id_str = f"{asa['ActCode']}_{asa['SectionCode']}"
            # Map to legal_layer section_id format (ITACT->IT)
            act_map = {"ITACT": "IT", "BNS": "BNS", "PMLA": "PMLA",
                       "BSA": "BSA", "BNSS": "BNSS"}
            prefix = act_map.get(asa["ActCode"], asa["ActCode"])
            section_node_id = f"{prefix}_{asa['SectionCode']}"
            edges.append({
                ":START_ID":    cm_id,
                ":END_ID":      section_node_id,
                ":TYPE":        "CHARGED_UNDER",
                "source_fir_id": cm_id,
            })
    return edges
